[common]
platform  = espressif32
board     = esp32-c2-devkitm-1
framework = arduino

board_build.flash_size  = 4MB
board_upload.flash_size = 4MB
monitor_speed = 115200
lib_ldf_mode  = deep+

lib_deps =
    adafruit/Adafruit ST7735 and ST7789 Library @ ^1.10.4
    adafruit/Adafruit GFX Library @ ^1.11.10
    bblanchon/ArduinoJson @ ^7.0.0
    mlesniew/PicoMQTT

; WICHTIG: keine ;-Kommentare INNERHALB der build_flags -> frisst die Folgezeile!
; Die -I Network/src Zeile ist der Fix gegen "Network.h: No such file or directory".
build_flags =
    -DCORE_DEBUG_LEVEL=0
    -I "${platformio.packages_dir}/framework-arduinoespressif32/libraries/Network/src"
    -DARDUINO_ARCH_ESP32
    -DBOARD_C2_PULT
    -I include
    -I fonts
    -I Icons

board_build.partitions = min_spiffs.csv

[env:esp32-c2-usb]
extends      = common
upload_speed = 921600

[env:esp32-c2-ota]
extends         = common
upload_protocol = espota
upload_port     = 192.168.0.41
upload_flags    =
    --port=3232
    --auth=dasdaDadaDAsdsadaDASdd